feat: add CrossFacilityReport schema
saivaai/saiva-api pull request #1
Opened 2024-03-25 13:27 UTC by marianakozyra

2024-03-25 21:21 UTC, mjurenka requested changes

2024-03-25 21:21 UTC, mjurenka commented on schema/CrossFacilityReport.json
> +                "unit",
this is marked as optional few lines above

2024-03-25 21:21 UTC, mjurenka commented on schema/CrossFacilityReport.json
> +                "rank_yesterday",
rank yesterday is definitely an optional field

2024-03-26 10:47 UTC, mjurenka commented
@VanesSaiva please take a look at this

2024-03-26 10:49 UTC, matusblhs approved these changes

2024-03-26 13:57 UTC, mjurenka approved these changes
approved

2024-03-26 13:57 UTC, merged